[2024-02-12 07:55:24,407] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_city scheduled__2024-02-11T07:44:56.593240+00:00 [queued]>
[2024-02-12 07:55:24,412] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_city scheduled__2024-02-11T07:44:56.593240+00:00 [queued]>
[2024-02-12 07:55:24,413] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 07:55:24,413] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 07:55:24,413] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 07:55:24,418] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_city> on 2024-02-11 07:44:56.593240+00:00
[2024-02-12 07:55:24,421] {standard_task_runner.py:52} INFO - Started process 10711 to run task
[2024-02-12 07:55:24,423] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_d_city', 'scheduled__2024-02-11T07:44:56.593240+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmp2z44_6gh', '--error-file', '/tmp/tmplp6n3bva']
[2024-02-12 07:55:24,423] {standard_task_runner.py:80} INFO - Job 241: Subtask update_d_city
[2024-02-12 07:55:24,455] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_d_city scheduled__2024-02-11T07:44:56.593240+00:00 [running]> on host 91766ce79ef0
[2024-02-12 07:55:24,490] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_d_city
AIRFLOW_CTX_EXECUTION_DATE=2024-02-11T07:44:56.593240+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-11T07:44:56.593240+00:00
[2024-02-12 07:55:24,496] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 07:55:24,500] {sql.py:315} INFO - Running statement: insert into mart.d_city (city_id, city_name)
select city_id, city_name from staging.user_order_log
where city_id not in (select city_id from mart.d_city)
group by city_id, city_name;, parameters: None
[2024-02-12 07:55:24,501] {sql.py:324} INFO - Rows affected: 0
[2024-02-12 07:55:24,511] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_d_city, execution_date=20240211T074456, start_date=20240212T075524, end_date=20240212T075524
[2024-02-12 07:55:24,555] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 07:55:24,577] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
