[2024-02-12 08:18:55,590] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_city scheduled__2024-02-10T08:09:37.968777+00:00 [queued]>
[2024-02-12 08:18:55,595] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_city scheduled__2024-02-10T08:09:37.968777+00:00 [queued]>
[2024-02-12 08:18:55,595] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 08:18:55,595] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 08:18:55,595] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 08:18:55,601] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_city> on 2024-02-10 08:09:37.968777+00:00
[2024-02-12 08:18:55,603] {standard_task_runner.py:52} INFO - Started process 14878 to run task
[2024-02-12 08:18:55,605] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_d_city', 'scheduled__2024-02-10T08:09:37.968777+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmpuulzbt5s', '--error-file', '/tmp/tmpl_n6vxos']
[2024-02-12 08:18:55,605] {standard_task_runner.py:80} INFO - Job 345: Subtask update_d_city
[2024-02-12 08:18:55,636] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_d_city scheduled__2024-02-10T08:09:37.968777+00:00 [running]> on host 91766ce79ef0
[2024-02-12 08:18:55,671] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_d_city
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T08:09:37.968777+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T08:09:37.968777+00:00
[2024-02-12 08:18:55,677] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 08:18:55,681] {sql.py:315} INFO - Running statement: insert into mart.d_city (city_id, city_name)
select city_id, city_name from staging.user_order_log
where city_id not in (select city_id from mart.d_city)
group by city_id, city_name;, parameters: None
[2024-02-12 08:18:55,682] {sql.py:324} INFO - Rows affected: 0
[2024-02-12 08:18:55,691] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_d_city, execution_date=20240210T080937, start_date=20240212T081855, end_date=20240212T081855
[2024-02-12 08:18:55,737] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 08:18:55,762] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
