[2024-02-12 10:15:15,649] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-10T10:05:47.421232+00:00 [queued]>
[2024-02-12 10:15:15,654] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-10T10:05:47.421232+00:00 [queued]>
[2024-02-12 10:15:15,654] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:15:15,654] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 10:15:15,654] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:15:15,659] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_item> on 2024-02-10 10:05:47.421232+00:00
[2024-02-12 10:15:15,662] {standard_task_runner.py:52} INFO - Started process 21985 to run task
[2024-02-12 10:15:15,663] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_d_item', 'scheduled__2024-02-10T10:05:47.421232+00:00', '--job-id', '488', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmpg0cwpyug', '--error-file', '/tmp/tmp60fawzh2']
[2024-02-12 10:15:15,664] {standard_task_runner.py:80} INFO - Job 488: Subtask update_d_item
[2024-02-12 10:15:15,698] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-10T10:05:47.421232+00:00 [running]> on host 91766ce79ef0
[2024-02-12 10:15:15,733] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_d_item
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T10:05:47.421232+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T10:05:47.421232+00:00
[2024-02-12 10:15:15,739] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 10:15:15,742] {sql.py:315} INFO - Running statement: insert into 
    mart.d_item (item_id, 
        item_name)
select 
    item_id, 
    item_name 
from staging.user_order_log
where item_id not in (select item_id from mart.d_item)
group by item_id, item_name, parameters: None
[2024-02-12 10:15:15,743] {sql.py:324} INFO - Rows affected: 0
[2024-02-12 10:15:15,751] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_d_item, execution_date=20240210T100547, start_date=20240212T101515, end_date=20240212T101515
[2024-02-12 10:15:15,796] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 10:15:15,820] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
