[2024-02-12 10:09:24,852] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-07T10:05:47.421232+00:00 [queued]>
[2024-02-12 10:09:24,857] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-07T10:05:47.421232+00:00 [queued]>
[2024-02-12 10:09:24,857] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:09:24,857] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 10:09:24,857] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:09:24,863] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_item> on 2024-02-07 10:05:47.421232+00:00
[2024-02-12 10:09:24,865] {standard_task_runner.py:52} INFO - Started process 19790 to run task
[2024-02-12 10:09:24,867] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_d_item', 'scheduled__2024-02-07T10:05:47.421232+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmp_f8aa6f5', '--error-file', '/tmp/tmp63dyckgn']
[2024-02-12 10:09:24,867] {standard_task_runner.py:80} INFO - Job 428: Subtask update_d_item
[2024-02-12 10:09:24,898] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_d_item scheduled__2024-02-07T10:05:47.421232+00:00 [running]> on host 91766ce79ef0
[2024-02-12 10:09:24,932] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_d_item
AIRFLOW_CTX_EXECUTION_DATE=2024-02-07T10:05:47.421232+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-07T10:05:47.421232+00:00
[2024-02-12 10:09:24,939] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 10:09:24,942] {sql.py:315} INFO - Running statement: insert into 
    mart.d_item (item_id, 
        item_name)
select 
    item_id, 
    item_name 
from staging.user_order_log
where item_id not in (select item_id from mart.d_item)
group by item_id, item_name, parameters: None
[2024-02-12 10:09:24,943] {sql.py:324} INFO - Rows affected: 0
[2024-02-12 10:09:24,951] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_d_item, execution_date=20240207T100547, start_date=20240212T100924, end_date=20240212T100924
[2024-02-12 10:09:24,959] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 10:09:24,980] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
