[2024-02-12 14:09:57,131] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.staging_schema_create scheduled__2024-02-10T14:01:59.240675+00:00 [queued]>
[2024-02-12 14:09:57,136] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.staging_schema_create scheduled__2024-02-10T14:01:59.240675+00:00 [queued]>
[2024-02-12 14:09:57,136] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:09:57,136] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 14:09:57,136] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:09:57,143] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): staging_schema_create> on 2024-02-10 14:01:59.240675+00:00
[2024-02-12 14:09:57,145] {standard_task_runner.py:52} INFO - Started process 30202 to run task
[2024-02-12 14:09:57,147] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'staging_schema_create', 'scheduled__2024-02-10T14:01:59.240675+00:00', '--job-id', '601', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmprykl1htx', '--error-file', '/tmp/tmp8ttbjjrc']
[2024-02-12 14:09:57,147] {standard_task_runner.py:80} INFO - Job 601: Subtask staging_schema_create
[2024-02-12 14:09:57,180] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.staging_schema_create scheduled__2024-02-10T14:01:59.240675+00:00 [running]> on host 91766ce79ef0
[2024-02-12 14:09:57,217] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=staging_schema_create
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T14:01:59.240675+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T14:01:59.240675+00:00
[2024-02-12 14:09:57,225] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 14:09:57,228] {sql.py:315} INFO - Running statement: create schema if not exists staging;

CREATE table if not exists staging.user_order_log (
	uniq_id varchar(32) NOT NULL,
	date_time timestamp NOT NULL,
	city_id int4 NOT NULL,
	city_name varchar(100) NULL,
	customer_id int4 NOT NULL,
	first_name varchar(100) NULL,
	last_name varchar(100) NULL,
	item_id int4 NOT NULL,
	item_name varchar(100) NULL,
	quantity int8 NULL,
	payment_amount numeric(10, 2) NULL,
	status varchar(15),
	CONSTRAINT user_order_log_pk PRIMARY KEY (uniq_id)
);
CREATE INDEX if not exists uo1 ON staging.user_order_log USING btree (customer_id);
CREATE INDEX if not exists uo2 ON staging.user_order_log USING btree (item_id);
alter table if exists staging.user_order_log add column if not exists status varchar(15);

create table if not exists staging.customer_research(
	date_id timestamp,
	category_id int,
	geo_id int,
	sales_qty int,
	sales_amt numeric(14,2)
);

create table if not exists staging.user_activity_log(
	uniq_id varchar(100),
	action_id bigint,
	customer_id bigint,
	date_time timestamp,
	quantity bigint
);

create table if not exists staging.price_log(
	name varchar(100),
	price int
);

create table if not exists mart.f_customer_retention
(
	new_customers_count int,
	returning_customers_count int,
	refunded_customer_count int,
	period_name varchar(100),
	period_id bigint,
	item_id bigint,
	new_customers_revenue bigint,
	returning_customers_revenue bigint,
	customers_refunded int,
	constraint f_customer_retention_pk primary key (period_name, period_id, item_id),
	CONSTRAINT f_customer_retention_item_id_fkey FOREIGN KEY (item_id) REFERENCES mart.d_item(item_id)
);, parameters: None
[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  schema "staging" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  relation "user_order_log" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  relation "uo1" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  relation "uo2" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  column "status" of relation "user_order_log" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  relation "customer_research" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  relation "user_activity_log" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  relation "price_log" already exists, skipping

[2024-02-12 14:09:57,229] {postgres.py:96} INFO - NOTICE:  relation "f_customer_retention" already exists, skipping

[2024-02-12 14:09:57,238] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=staging_schema_create, execution_date=20240210T140159, start_date=20240212T140957, end_date=20240212T140957
[2024-02-12 14:09:57,278] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 14:09:57,302] {local_task_job.py:273} INFO - 4 downstream tasks scheduled from follow-on schedule check
